from api.models import Category, Product
c1 = Category.objects.create(name='Smartphones')
c2 = Category.objects.create(name='Laptops')
c3 = Category.objects.create(name='Headphones')
c4 = Category.objects.create(name='Appliances')
c5 = Category.objects.create(name='Other')
Product.objects.create(name='Apple iPhone 15 128Gb', price=405613, description='Apple iPhone 15...', count=10, category=c1)
Product.objects.create(name='Samsung Galaxy S24 Ultra 5G', price=597997, description='Samsung Galaxy S24 Ultra 5G...', count=10, category=c1)
Product.objects.create(name='Xiaomi Redmi Note 13 Pro+ 5G', price=184462, description='Xiaomi Redmi Note 13 Pro+...', count=10, category=c1)
Product.objects.create(name='Poco X6 Pro 12 ГБ/512 ГБ', price=228094, description='Poco X6 Pro 5G...', count=10, category=c1)
Product.objects.create(name='Apple MacBook Air 13 2022 13.6"', price=799800, description='MacBook Air 2022 года можно назвать одним из крупнейших обновлений...', count=10, category=c2)
Product.objects.create(name='Lenovo IdeaPad 3 15.6" 81WQ00ERRK', price=172985, description='Ноутбук IdeaPad 3 работает тише...', count=10, category=c2)
Product.objects.create(name='ASUS TUF Gaming FA507NUR', price=824890, description='ASUS TUF Gaming — это мощный и надёжный ноутбук...', count=10, category=c2)
Product.objects.create(name='HP Pavilion 15-eh3007ci 15.6"', price=449999, description='Мощный и стильный ноутбук с ярким экраном 15.6"...', count=10, category=c2)
Product.objects.create(name='Lenovo IdeaPad 3 15.6" 256GB', price=250000, description='Ноутбук IdeaPad 3 работает тише и с меньшим выделением тепла...', count=10, category=c2)
Product.objects.create(name='Apple AirPods 4 Active Noise Cancellation', price=84705, description='Обновленные беспроводные наушники Apple AirPods 4...', count=10, category=c3)
Product.objects.create(name='Marshall Major IV черный', price=23997, description='Bluetooth гарнитура MARSHALL Major IV подарит вам комфорт...', count=10, category=c3)
Product.objects.create(name='Sony WH-1000XM5 черный', price=133633, description='WH-1000XM5 поддерживают форматы High-Resolution Audio...', count=10, category=c3)
Product.objects.create(name='Samsung Galaxy Buds 2 зеленый', price=85989, description='Усовершенствованная двухполосная акустика и активное шумоподавление...', count=10, category=c3)
Product.objects.create(name='JBL Tune 510BT черный', price=11398, description='Наушники JBL Tune 510BT позволяют наслаждаться мощными басами...', count=10, category=c3)
Product.objects.create(name='Dyson Airwrap HS05 Long с дорожным чехлом', price=286827, description='Самая полная комплектация, включающая помимо стайлера и 6 насадок, бархатную сумку.', count=10, category=c4)
Product.objects.create(name='Робот-пылесос Xiaomi Robot Vacuum E10 белый', price=85000, description='Чистота без рук.', count=10, category=c4)
Product.objects.create(name='Микроволновая печь Samsung MS20A7013AB/BW', price=124990, description='Выберите встраиваемую микроволновую печь, которая идеально впишется в дизайн вашей кухни.', count=10, category=c4)
Product.objects.create(name='Электрочайник Tefal Glass KI840830', price=23990, description='Электрочайник Tefal Glass KI840830 — стильный и функциональный помощник на вашей кухне.', count=10, category=c4)
Product.objects.create(name='Блендер погружной Braun MQ 535 Sauce белый', price=39990, description='Блендер Braun MQ535 Sauce серо-белого цвета – мультиповар на вашей кухне.', count=10, category=c4)